<a href="https://colab.research.google.com/github/jlin246/Micro-credentials-Jan-2022-BSNS/blob/main/python/Unit%203/Unit_3_Lect_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as numpy
import numpy as np
a = np.array([1,2,3,9], dtype='int32')
print(a)

[1 2 3 9]


In [ ]:
arr = numpy.array([121,123,127,140,125,133,141,130,129,])
x = numpy.amax(arr)
print(x)

141


In [ ]:
arr = numpy.array([121,123,127,140,125,133,141,130,129,])

x = numpy.std(arr)
print(x)

print(numpy.min(arr))

print(numpy.mean(arr))

6.623937138128391
121
129.88888888888889


In [ ]:
import numpy as np
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
print(b.size)
#Elements
print(b.itemsize)
#itemsize() function return the length of one array element in bytes.
b.shape


[[9. 8. 7.]
 [6. 5. 4.]]
6
8


(2, 3)

In [ ]:
b.ndim

2

In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
#Get shape (tuples)
a.shape

(4,)

In [ ]:
 #Get Type
a.dtype

dtype('int32')

In [ ]:
# Get Size
a.itemsize

4

In [ ]:
#Get number of elements
a.size

4

In [ ]:
import numpy as np
c= np.array([13.1,2,3,9])
print(c)
print(c.itemsize)
c.size

[13.1  2.   3.   9. ]
8


4

In [ ]:
import numpy as np
cars= np.array(['dodge','jeep','bmw'], dtype=str)
print(cars)

['dodge' 'jeep' 'bmw']


In [ ]:
cars.shape

(3,)

In [ ]:
cars.size

3

In [ ]:
cars.ndim

1

In [ ]:
cars.itemsize

20

In [ ]:
cars.dtype

dtype('<U5')


Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a[1,0],a[1,2])


8 10


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
d=np.ones((4,2), dtype='int32')
d

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

Mathematics/can perform basic +,-,/,* and advanced operations

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
# adding two arrays ,is adding each element by element/They have to be the same size
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

Accessing Elements of Array 

In [ ]:
a = np.array([17,2,3,4])
print(a[0])
a[3]

17


4

In [ ]:
w=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(w)
print(w[0,0])
print(w[1,3])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
1
11


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


*******Finding value greater or less < x >  in Array********** Assignment 

In [ ]:
import numpy as np
studentscore = np.array([56,87,43,68,90])

#Set condition
passingscore=studentscore>60
print(passingscore)

#List values
studentscore[passingscore]

[False  True False  True  True]


array([87, 68, 90])

Copy and view (slide 18)
When working with arrays, data is copied into new arrays only in some cases. 

In [ ]:
import numpy as np
cars= np.array(['dodge','jeep','bmw'])
print(cars)
autos=cars
print(autos)
#show both subjects are the same
print(cars is autos)
print(len (autos))
autos[1]='benz'
print(autos)
print(cars)


['dodge' 'jeep' 'bmw']
['dodge' 'jeep' 'bmw']
True
3
['dodge' 'benz' 'bmw']
['dodge' 'benz' 'bmw']


Some times we want to manuplate an array but keep a copy of older version

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


(Ufunc) Universall functions ,ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.

In [ ]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [ ]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
print(newarr)
newarr=arr1 - arr2
newarr
print(newarr)

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]


In [ ]:
import numpy as np

arr1 = ([10, 11, 45, 180, 90, 0])
print(np.cos(arr1))
print(np.sqrt(arr1)) 

[-0.83907153  0.0044257   0.52532199 -0.59846007 -0.44807362  1.        ]
[ 3.16227766  3.31662479  6.70820393 13.41640786  9.48683298  0.        ]


Transposing array (a = mxn, a^T = nxm)

In [ ]:
import numpy as np
ary = np.array([[1, 2, 3], [4, 5, 6]])
print(ary)
np.transpose(ary)
print(np.transpose(ary))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Statistics on Arrays

*******Finding min ,max values in Array********** Assignment

In [ ]:
#Find Max number in Array
score = np.array([[1,2,3],[4,5,6]])
score

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(np.min(score))
print(np.max(score))


1
6


Assignment Unit_2,L1
Find maximum value & its index in a 1D Numpy Array:

In [ ]:
#Find maximum value & its index in a 1D Numpy Array:
import numpy as np
num = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
print(np.max(num))
print(np.min(num))
print(np.std(num))

17
11
1.9948914348241347


In [ ]:
import numpy as np
num = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])

Find index of maximum value :
Get the array of indices of maximum value in numpy array using numpy.where() *italicized text*

In [ ]:
# Get the max and indices of maximum element in numpy array
import numpy as np
num = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
result = np.where(num == np.max(num)) #create variable which will have the value of the max element in array (num in this case)
print('return max value',np.max(num))
print('Returned tuple of arrays :', result) # 
print('List of Indices of maximum element :', result[0])#,result[0] is the variable where [0] indicates where in the array the max value is

print('return min value:', np.min(num))
print('returned tuple of arrays :', np.where(num == np.min(num)))
print('list of indices of minimum element :', np.where(num == np.min(num))[0])

return max value 17
Returned tuple of arrays : (array([ 6, 13]),)
List of Indices of maximum element : [ 6 13]
return min value: 11
returned tuple of arrays : (array([0, 8]),)
list of indices of minimum element : [0 8]


In [ ]:
#Dataset from summer Olympic London, year 2012
import numpy as np
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,17,14])
highest = np.where(np_olympic_country_Gold== np.max(np_olympic_country_Gold))
print('Max number of gold medals',np.max(np_olympic_country_Gold ))
print('index number of maximum element (gold medals) :', highest[0])
print('The country with Max number of gold medals is:',np_olympic_country[highest])
print('\n')
more_than_20_medals=np_olympic_country_Gold >20
print(more_than_20_medals)
np_olympic_country_Gold[more_than_20_medals]
x = np.where(np_olympic_country_Gold >20)

print('the countries with more than 20 medals are:',np_olympic_country[x])
print('\n')

lowest = np.where(np_olympic_country_Gold == np.min(np_olympic_country_Gold))
print('Minimum number of gold medals: ', np.min(np_olympic_country_Gold))
print('index number of minimum element (gold medals): ', lowest[0])
print('the country with min number of gold medals is ', np_olympic_country[lowest])

Max number of gold medals 46
index number of maximum element (gold medals) : [3]
The country with Max number of gold medals is: ['US']


[ True  True  True  True False False False]
the countries with more than 20 medals are: ['GBR' 'China' 'RUS' 'US']


Minimum number of gold medals:  7
index number of minimum element (gold medals):  [5]
the country with min number of gold medals is  ['JPN']


In [ ]:
#Find countrieas with more than 20 gold metals
import numpy as np
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
more_than_20_medals=np_olympic_country_Gold >20
print(more_than_20_medals)
np_olympic_country_Gold[more_than_20_medals]
x = np.where(np_olympic_country_Gold >20)

print(x)



[ True  True  True  True False False False]
(array([0, 1, 2, 3]),)
